### ISSUE TITLE
OpenNeuro data download failure on Windows

### ISSUE THREAD

**Issue by dyt811** [illdopejake/RS2018_Nilearn_tutorial#1]
## Symptom:
- setup.bat will crash and disappear, masking the issue that 14GB data were never downloaded. 
- Manual invocation of the download script provided more details of the error: ![](https://user-images.githubusercontent.com/6720068/46166371-0a95b600-c261-11e8-9330-d53addcbb2de.png)

## Comments: 
- Investigation suggest the error may be related with ":" in the path name from OpenNeuro data repo.
- Attempted multiple invocation of the download python script with shorter saving location still does not resolve the issue. 

## Expected Behavior:
- Download should succeed without stack trace.

**Comment by illdopejake** [comment]
We've been able to reproduce this on another computer. We were able to fix it by manually editing the utils.py script directly in the nilearn package. Specifically:

There is a function _fetch_files parses the URL that you feed it and uses that to create a filename to download on your own computer. The problem is that the URL has a : and windows apparently doesn't understand that. By manually changing line 502 (below), we were able to surmount the issue and start the download:
https://github.com/nilearn/nilearn/blob/master/nilearn/datasets/utils.py#L502

As far as we can tell, after the download, the file is moved to a user-supplied filename (supplied in download.py). It may also be necessary to add some lines directly to download.py to address this : issue there as well.

This is obviously not a solution for the end user but at least we have an eye on the issue. Still working to make a more workable fix...

**Comment by GaelVaroquaux** [comment]
I have pushed what I believe is a fix. However, I do not have a windows
computer to check.

**Comment by illdopejake** [comment]
This fix seems to have worked!

**Comment by dyt811** [comment]
I think the issue has not been fully resolved, even after deleting previous environment, recloning the repo and trying again:  
![image](https://user-images.githubusercontent.com/6720068/46180812-8fe48f00-c290-11e8-84f5-09ba03b0fbde.png)

**Comment by illdopejake** [comment]
It seems there is a hard-coded path with a slash that windows doesn't like

**Comment by GaelVaroquaux** [comment]
Indeed, I had done a mistake. Can you try now?

**Comment by crocodoyle** [comment]
Running `python download.py` now appears to work on Windows, this conference wifi is the worst though so I can't test fully

**Comment by dyt811** [comment]
Hi, all. Seems the issue is still not fully fixed: 

![image](https://user-images.githubusercontent.com/6720068/46220313-bb5e8c80-c317-11e8-8d20-3e606b0326e9.png)

Odd that the colon fix worked for earlier data sequences but not the others.

**Comment by illdopejake** [comment]
This is because all the data has downloaded but looks like now it's moving on to the confounds and the issue returns

**Comment by GaelVaroquaux** [comment]
Should be fixed now.

**Comment by dyt811** [comment]
Great. The rest of the download finished successfully without issue. All good now. Much thanks. @GaelVaroquaux @illdopejake .
